### ISSUE TITLE
Make mpc sign recovery param unmodified

### ISSUE THREAD

**Issue by ieow** [Web3Auth/mpc-core-kit#122]
recovery param modification should be handled by provider.
remove modification for v3
 ```
 v= v+27
 ```

**Comment by himanshuchawla009** [comment]
but wht if apps dont want to use our provider and rather wants to use provider like viem just like wht pancake swap is doing.

**Comment by matthiasgeihs** [comment]
> but wht if apps dont want to use our provider and rather wants to use provider like viem just like wht pancake swap is doing.

They can always add back the `+27`? In fact, Pancake Swap are already checking for it ([signing.ts#L41](https://github.com/pancakeswap/pancake-mobile-private/blob/915d3cd10b04d1a246dafb247b7119768282e994/src/lib/mpc/signing.ts#L41)).

**Comment by himanshuchawla009** [comment]
merged in v3
