### ISSUE TITLE
Remove Provider from mpc-core-kit

### ISSUE THREAD

**Issue by ieow** [Web3Auth/mpc-core-kit#123]
mpc core kit will be injected in to Ethereum Provider instead of being setup in mpc core kit

**Comment by yashovardhan** [comment]
While doing this, is it possible to extend the same secp256k1 based signatures for a cosmos and bitcoin provider as well? Is it possible for us as DevRel team to make multiple providers like these on community/ customer request?

**Comment by ieow** [comment]
As long as other provider accept interface with function sign and getPublicKey, we could adapt and inject in to the provider

**Comment by himanshuchawla009** [comment]
merged in v3
