### ISSUE TITLE
Implicit atomic mutation

### ISSUE THREAD

**Issue by ieow** [Web3Auth/mpc-core-kit#125]
Currently for manual Sync = false, tkey is updating metadata for every mutation ( some mpc function invoked multiple mutation).
with manual sync = true, developer have to call commitChanges after every mpc function call that invoked mutation.

adding implicit atomic mutation so that for mpc function that invoked multiple mutation will only invoke once after all local mutation is done for manual Sync = false in mpc-core-kit.

**Comment by himanshuchawla009** [comment]
merged in v3
