### ISSUE TITLE
Ability to export keys for indexed accounts

### ISSUE THREAD

**Issue by yashovardhan** [Web3Auth/mpc-core-kit#143]
With our multi accounts feature of the SDK, we can easily sign and create new MPC accounts, however when we try to export the private key, it only exports for the base account, and not for all indexed accounts.

The private key `using ._UNSAFE_exportTssKey()` is the same for all accounts.

**Steps to reproduce:**
- Create 2 accounts
- Switch to index 0, get private key (using .setTssWalletIndex(0))
- Switch to index 1, get private key (using .setTssWalletIndex(1))

**Expected results:** For each account returned a unique private key.
**Actual results:** Identical private keys returned for both accounts.

**Comment by AyushBherwani1998** [comment]
Works fine in v3 alpha 3

**Comment by matthiasgeihs** [comment]
Resolved in #147
