### ISSUE TITLE
[v3] toString("base64") is not working in React Native

### ISSUE THREAD

**Issue by ieow** [Web3Auth/mpc-core-kit#152]
```
    const client = new Client(
      currentSession,
      clientIndex,
      partyIndexes,
      endpoints,
      sockets,
      share,
      tssPubKey.toString("base64"),
      true,
      this._tssLib.lib
    );
 ```
tssPubKey.toString("base64") is returning string in the format below
` "151,204,165,141,226,194,173,159,241,182,25,4,224,242,100,86,48,161,37,250,239,236,228,210,84,196,26,128,177,210,204,60,22,217,37,190,164,92,184,50,133,42,164,242,38,8,209,229,108,145,78,193,171,242,0,175,17,124,49,27,118,237,74,67"`

instead of base64 format

**Comment by matthiasgeihs** [comment]
Resolved in #153
