### ISSUE TITLE
V3: Fix tss lib types

### ISSUE THREAD

**Issue by matthiasgeihs** [Web3Auth/mpc-core-kit#156]
Due to a packaging mistake in the tss libs, the tss lib types are currently not packaged correctly. We should merge the fixes and update the dependencies here before releasing V3. @himanshuchawla009 

* https://github.com/torusresearch/tss-client/pull/66
* https://github.com/torusresearch/tss-server/pull/146

**Comment by metalurgical** [comment]
These have been merged
