### ISSUE TITLE
[v3] _UNSAFE_exportTssKey doesn't work for ed25519

### ISSUE THREAD

**Issue by AyushBherwani1998** [Web3Auth/mpc-core-kit#157]
## Description 
When the keyType is ed25519, the `_UNSAFE_exportTssKey` returns the SEC1 format key instead of ed25519. Ideally if exporting ed25519 key is not supported it should throw an error. 

<img width="337" alt="Screenshot_2024-06-18_at_10 05 44_AM" src="https://github.com/Web3Auth/mpc-core-kit/assets/34301187/1db8f862-9bcf-4b01-9fcf-4ee94e379c29">

**Comment by metalurgical** [comment]
From what I can tell from the codebase.

This function should be being called here instead (this outputs the seed).
```
_UNSAFE_exportTssEd25519Seed
```

Please double check.

**Comment by metalurgical** [comment]
`_UNSAFE_exportTssKey`, by itself, will not return the correct value for ed25519 by itself.

It is actually called as part of the above function.

**Comment by metalurgical** [comment]
https://github.com/Web3Auth/mpc-core-kit/pull/160

**Comment by matthiasgeihs** [comment]
There is a few caveats here: Export seed is only available if the seed has been imported. (I.e., if the account was setup with the ed25519 import key flow.) Otherwise, we don't have the ed25519 seed, because the DKG doesn't produce a seed, just the scalar.

**Comment by himanshuchawla009** [comment]
> There is a few caveats here: Export seed is only available if the seed has been imported. (I.e., if the account was setup with the ed25519 import key flow.) Otherwise, we don't have the ed25519 seed, because the DKG doesn't produce a seed, just the scalar.

i think we still create a seed on frontend and save it encrypted with the scalar. Will revisit this.

**Comment by matthiasgeihs** [comment]
@himanshuchawla009 we don't, i tested the export seed flow for a fresh account (using demo) and then encountered the issue. afterwards went through the code to confirm. but feel free to double check. the reasoning why this is actually a valid approach: if we would generate the seed in the frontend and then store it and share it (like import flow just generate seed at random), we would create a single point of failure, which we typically don't want with MPC.

**Comment by AyushBherwani1998** [comment]
@matthiasgeihs fix works fine, tested flow with importing seed, and without importing seed.
