### ISSUE TITLE
README: broken image link

### ISSUE THREAD

**Issue by matthiasgeihs** [Web3Auth/mpc-core-kit#22]
The quick start section of the README references the image at https://camo.githubusercontent.com/b6bd3df91c1791160c444aa71fc557775a245f2a15177953e9262807738e75c9/68747470733a2f2f77656233617574682e696f2f646f63732f6173736574732f696d616765732f70726f6a6563745f706c75675f6e5f706c61792d38396333396563343261643939333130376262323438356231636536346238392e706e67.

However, this image does not seem to be served anymore.

**Comment by ieow** [comment]
Fixed in #58
